# format below string
product_qualifier_query = (
    "SELECT "
    "opi.source_item_code                             item,"
    "JSON_OBJECT "
    " ('item' VALUE opi.source_item_code, 'wh_item_code' VALUE opi.wh_item_code, 'item_gl' VALUE opi.item_gl, 'department' VALUE opi.department_code, "
    " 'facility' VALUE opi.organization_code, "
    " 'lc' VALUE opi.link_code, 'company_code' VALUE opi.company_code, 'division' VALUE opi.division_id, 'gs_item_type' "
    " VALUE opi.gs_item_type, 'shipper' VALUE opi.shipper_flag, "
    " 'pallet_size' VALUE opi.pallet_size) async_prod, "
    " ( "
    " SELECT "
    " JSON_OBJECT "
    " ('product_qualifier' VALUE opc.product_qualifier, 'product_qualifier_val' VALUE opc.product_qualifier_val, 'pricing_data' "
    " VALUE json_arrayagg( "
    " JSON_OBJECT "
    " ('price_source_group' VALUE opc.price_source_group, 'price_source' VALUE opc.price_source, 'price_source_sub_type' VALUE opc. "
    " price_source_sub_type, 'pricing_data' VALUE opc.pricing_data RETURNING clob) RETURNING clob) RETURNING clob) "
    " FROM "
    " apps.oms_prc_combinations opc "
    " WHERE "
    " opc.division_id = 2 "
    " AND opc.product_qualifier_val = opi.wh_item_code "
    " AND opc.product_qualifier = 'ITEM' "
    " GROUP BY "
    " opc.product_qualifier, "
    " opc.product_qualifier_val "
    " )                                                async_comb, "
    "( "
    " SELECT "
    "   JSON_OBJECT "
    " ('product_qualifier' VALUE oppr.product_qualifier, 'product_qualifier_val' VALUE oppr.product_qualifier_val, 'product_refs' "
    " VALUE json_arrayagg( "
    "     JSON_OBJECT "
    " ('price_source_group' VALUE oppr.price_source_group, 'price_source' VALUE oppr.price_source, 'price_source_sub_type' VALUE "
    "  oppr.price_source_sub_type, 'reference_keys' VALUE oppr.reference_keys, 'incl_excl' VALUE incl_excl RETURNING clob) RETURNING "
    " clob) RETURNING clob) product_references "
    "FROM "
    "    apps.oms_prc_product_refs oppr "
    " WHERE "
    "        oppr.division_id = 2 "
    "    AND oppr.product_qualifier_val = opi.wh_item_code "
    "    AND oppr.product_qualifier = 'ITEM' "
    " GROUP BY "
    "    oppr.product_qualifier, "
    "    oppr.product_qualifier_val "
    " )                                                async_item_qf "
    " FROM "
    " apps.oms_prc_item_qualifiers_v opi "
    " WHERE "
    " opi.division_id = 2 "
    " AND opi.company_code IN ( '010' ) and opi.source_item_code is not null and rownum <= 100"
)
# " AND ROWNUM < 10 "
